const projects = [
  {
    id: "1",
    clientID: "1",
    name: "Project A",
    description: "Description A",
    status: 'true',
  },
  {
    id: "2",
    clientID: "2",
    name: "Project B",
    description: "Description B",
    status: 'false',
  },
  {
    id: "3",
    clientID: "3",
    name: "Project C",
    description: "Description C",
    status: 'true',
  },
  {
    id: "4",
    clientID: "4",
    name: "Project D",
    description: "Description D",
    status: 'false',
  },
  {
    id: "5",
    clientID: "5",
    name: "Project E",
    description: "Description E",
    status: 'true',
  },
  {
    id: "6",
    clientID: "6",
    name: "Project F",
    description: "Description F",
    status: 'false',
  },
  {
    id: "7",
    clientID: "7",
    name: "Project G",
    description: "Description G",
    status: 'true',
  },
  {
    id: "8",
    clientID: "8",
    name: "Project H",
    description: "Description H",
    status: 'false',
  },
  {
    id: "9",
    clientID: "9",
    name: "Project I",
    description: "Description I",
    status: 'true',
  },
  {
    id: "10",
    clientID: "10",
    name: "Project J",
    description: "Description J",
    status: 'false',
  },
];
const clients = [
  {
    id: "1",
    name: "Client A",
    email: "clientA@example.com",
    phone: 1234567890.0,
  },
  {
    id: "2",
    name: "Client B",
    email: "clientB@example.com",
    phone: 2345678901.0,
  },
  {
    id: "3",
    name: "Client C",
    email: "clientC@example.com",
    phone: 3456789012.0,
  },
  {
    id: "4",
    name: "Client D",
    email: "clientD@example.com",
    phone: 4567890123.0,
  },
  {
    id: "5",
    name: "Client E",
    email: "clientE@example.com",
    phone: 5678901234.0,
  },
  {
    id: "6",
    name: "Client F",
    email: "clientF@example.com",
    phone: 6789012345.0,
  },
  {
    id: "7",
    name: "Client G",
    email: "clientG@example.com",
    phone: 7890123456.0,
  },
  {
    id: "8",
    name: "Client H",
    email: "clientH@example.com",
    phone: 8901234567.0,
  },
  {
    id: "9",
    name: "Client I",
    email: "clientI@example.com",
    phone: 9012345678.0,
  },
  {
    id: "10",
    name: "Client J",
    email: "clientJ@example.com",
    phone: 1234567890.0,
  },
];

module.exports = {projects, clients};